backend:
  name: github
  repo: MMing1999/zmh.life
  branch: main
  base_url: https://zmh.life
  auth_endpoint: auth
  client_id: Ov23liFESFb3Ul9cWPCj
  client_secret: 52b8dee32c77fbb476c5bee40edb781146d5f490

media_folder: "src/assets/Pics/xing"
public_folder: "/assets/Pics/xing"

collections:
  - name: "xing_entries"
    label: "行·Doing 项目"
    folder: "src/entries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "简介", name: "summary", widget: "text"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "分类", name: "categories", widget: "list"}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "封面", name: "cover", widget: "image"}
      - {label: "内容", name: "body", widget: "markdown"}
