backend:
  # 生产环境：使用 git-gateway + Auth0
  name: git-gateway
  branch: main
  auth_type: pkce
  
  # 本地开发时使用 local_backend（注释掉上面的，启用下面的）
  # name: local_backend

media_folder: "src/assets/Pics"   # 仓库中实际存图位置
public_folder: "/assets/Pics"     # 页面里引用的公开路径

site_url: "https://zmhlife.netlify.app"
logo_url: "/assets/Pics/Ellipse 1.png"

collections:
  - name: "projects"               # 集合 ID
    label: "行动库 · Projects"     # 后台左侧菜单名
    folder: "src/entries"     # 新建的 md 文件放这里
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    preview_path: "xing/{{slug}}/" # Eleventy 构建后的预览路径

    fields:
      # —— 文档基础设置（默认不显示给编辑者）——
      - { label: "布局（固定）", name: "layout", widget: "hidden", default: "layouts/project.njk" }
      - { label: "分区（固定）", name: "section", widget: "hidden", default: "xing" }
      - { label: "页面样式（固定）", name: "pageCSS", widget: "hidden", default: "/assets/Css/project.css" }

      # —— 封面图 —— 
      - { label: "封面图", name: "cover", widget: "image", allow_multiple: false, required: false }

      # —— 文档基本信息 —— 
      - { label: "标题", name: "title", widget: "string" }
      - { label: "摘要（用于卡片/SEO）", name: "summary", widget: "text", required: false }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }

      - label: "分类（可多选）"
        name: "categories"
        widget: "select"
        multiple: true
        required: false
        options: ["design", "art", "dev", "product", "startup"]

      - label: "标签（#tag）"
        name: "tags"
        widget: "list"
        required: false
        summary: "#{{fields.item}}"
        field: { label: "tag", name: "item", widget: "string" }

      # —— 可选信息（有则显示）——
      - { label: "时间周期", name: "period", widget: "string", required: false }

      - label: "工具"
        name: "tools"
        widget: "list"
        required: false
        field: { label: "工具", name: "item", widget: "string" }

      - { label: "客户", name: "client", widget: "string", required: false }

      - label: "合作者"
        name: "collaborators"
        widget: "list"
        required: false
        field: { label: "合作者", name: "item", widget: "string" }

      - { label: "报酬/价格", name: "fee", widget: "string", required: false }

      - label: "外链"
        name: "links"
        widget: "object"
        required: false
        fields:
          - { label: "演示 demo", name: "demo", widget: "string", required: false }
          - { label: "仓库 repo", name: "repo", widget: "string", required: false }
          - { label: "文档 doc",  name: "doc",  widget: "string", required: false }

      # —— 正文（Markdown）——
      - { label: "正文", name: "body", widget: "markdown" }